services:
  webapp:
    build: .
    volumes: 
      - .:/apps
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: erlan
      POSTGRES_PASSWORD: erlan
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erlan -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: