# Generated by Django 5.2 on 2025-05-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
