# Generated by Django 5.1.4 on 2025-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
