name: Django CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PostgreSQL
      run: |
        sudo apt update
        sudo apt install -y postgresql postgresql-contrib
        sudo service postgresql start
        
        # Check if the database exists
        if ! sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = 'test_db'" | grep -q 1; then
          sudo -u postgres psql -c "CREATE DATABASE test_db;"
        fi
        
        # Check if the role exists
        if ! sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname = 'erlan'" | grep -q 1; then
          sudo -u postgres psql -c "CREATE ROLE erlan WITH LOGIN PASSWORD 'erlan';"
        fi
        
        # Grant privileges to the role
        sudo -u postgres psql -c "ALTER ROLE erlan CREATEDB;"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test_db TO erlan;"

    # Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # Set environment variables for database
    - name: Set up environment variables
      run: echo "DATABASE_URL=postgres://erlan:erlan@localhost:5432/test_db" >> $GITHUB_ENV
    - name: Run Pylint
      run: |
        pylint apps/
    - name: Run Coverage
      run: |
        coverage run manage.py test
    - name: Run Coverage Report
      run: |
        coverage report
